dist: trusty

branches:
  only:
  - master
  - develop
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

language: node_js

cache:
  directories:
  - "$HOME/.npm"

node_js:
  - 10
  - 9
  - 8
  - "lts/*"

script:
  - npm run build
  - npm run test:unit

after_success:
  - npm install coveralls codacy-coverage
  - cat coverage/lcov.info | npx coveralls
  - cat coverage/lcov.info | npx codacy-coverage
