dist: trusty

branches:
  only:
  - master
  - develop
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

language: node_js

cache:
  directories:
  - "$HOME/.npm"

node_js:
  - 10

install:
  - npm ci
  - npm build

script:
  - npm run test:unit
  - npm run test:e2e-ci

